# fly.toml app configuration file generated for noah-rijkaard-url-shortner on 2024-08-20T21:09:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noah-rijkaard-url-shortner'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[build.args]
RAILS_MASTER_KEY="fed567ea51cf1ab4e8e70958198bdda0"

[deploy]
  # release_command = "bin/setup"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[restart]]
  policy = "always"

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    restart_limit = 2
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
